version: "3"

services: 
    mysql:
        container_name: "mysql"
        image: mysql:5.7
        volumes: 
            - db_data:/var/lib/mysql
        restart: always
        environment: 
            MYSQL_ROOT_PASSWORD: qwerty1234
            MYSQL_DATABASE: test_db
            MYSQL_USER: user_db
            MYSQL_PASSWORD: qwerty_db
        ports: 
            - 3306:3306
    api:
        container_name: "api"
        restart: always
        build: 
            context: ./arch
            dockerfile: Dockerfile
        ports:
            - 3000:3000
        volumes: 
            - ./arch:/src
        depends_on: 
            - mysql
        links:
            - mysql:mysql
        command: bash -c "npm install && npm run start:dev"
volumes: 
    db_data: {}            